Add a neutral button to the StateDialogActiviy that dismisses and mak…
syncthing/syncthing-android pull request #1828
Opened 2022-08-24 08:32 UTC by fps

…e the exit option stop the service and remove the activity from the tasklist (fixes #1814)
![Capture](https://user-images.githubusercontent.com/84968/186370408-09640cb4-9f37-4e07-9300-1c4c3e216ee8.PNG)

2022-08-25 07:42 UTC, imsodin requested changes
The exist button has to be conditional on `PREF_START_SERVICE_ON_BOOT       = "always_run_in_background"` (https://github.com/syncthing/syncthing-android/blob/892fdea2ea359830980d598b4fd2a016829906d4/app/src/main/java/com/nutomic/syncthingandroid/service/Constants.java#L16) just like in the main/sidebar menu. Respectively it could also be disabled (with something like a tooltip if that exists on android) instead of hidden. Generally I do prefer if UI elements don't dis/reappear but witout an explanation of why it's disable it might be better if it's not there at all.

2022-08-25 08:28 UTC, fps commented
Thanks for the review! Yeah, you're right about it being conditional on that preference. I'll have to ponder this for a little while..

2022-08-25 10:42 UTC, fps commented
I decided to remove the "dismiss" button again and basically make the exit button in the dialog work like the exit button in the DrawerFragment (i.e. stop the service only when it's not set to start at boot and remove the task from the tasklist in either case.)

2022-08-25 16:04 UTC, imsodin commented
There's no exit button at all in the drawer menu when set to start at boot. And generally I don't think it's a good idea having a button (not deactivated) which does nothing.

2022-08-26 11:27 UTC, fps commented
Hi again, the exit button does exist in the StateDialogActivity dialog though, even when the service is set to start at boot. So do you argue the exit button should not exist in that dialog either in case the service is set to start at boot?

2022-09-10 22:10 UTC, imsodin commented
Doesn't exist for me:

![Screenshot of Syncthing's menu without an exit entry](https://user-images.githubusercontent.com/15955093/189503381-2ce50ba7-a42e-4118-87d6-7522c27ef5c1.png)

Sorry again for the super long reaction time, I'll need to make a point of dedicating some fixed time to Syncthing - I really like doing it, it's just hard to allocate the time (that sounds like BS even to myself :P ).

2022-09-11 11:32 UTC, fps commented
Hi! No problem at all. There is no hurry :) I guess it's me running an older version again.. I will think about the dialog a bit more then...

2023-04-18 11:09 UTC, closed without merging